### ISSUE TITLE
Free Flight major bug

### ISSUE THREAD

**Issue by Lucawist** [StudioFolder/aerocene#10]
Most of the time, the Free Flight stops before even departing. 

The explorer, in the FF, is only one, but 8 explorers icons appear in the interface.

![screen shot 2018-02-23 at 17 00 10](https://user-images.githubusercontent.com/9106361/36607840-36b03942-18c8-11e8-8639-f2e6d4cb6c33.png)

**Comment by iacopolea** [comment]
@mariofaranda what is the expected behaviour here? 8 or 1 explorer?

**Comment by mariofaranda** [comment]
@iacopolea @angeloseme Anche la modalità Free Float deve avere 8 explorer. L'explorer "vincente" che viene selezionato alla fine sarà quello che avrà percorso una distanza complessiva maggiore.
