### ISSUE TITLE
Explorer Icons blue circle bug

### ISSUE THREAD

**Issue by Lucawist** [StudioFolder/aerocene#12]
The Explorer's blue circle, counting days, that appears in the interface, doesn't proceed correctly, shifting from the right days count. 
![screen shot 2018-02-23 at 18 32 41](https://user-images.githubusercontent.com/9106361/36607821-2390773c-18c8-11e8-8b5d-3c08fc4a05e7.png)

**Comment by iacopolea** [comment]
fixed in last release
