### ISSUE TITLE
Play/Pause malfunction

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#19]
Se metto in pausa l'animazione durante un volo e poi clicco sulla sfera per ruotarla, l'animazione torna in play in automatico. Questo non dovrebbe succedere, perché la modalità "in pausa" dovrebbe servire proprio ad esplorare il pianeta ad animazione ferma. 

Invece, è corretto (come già succede) che se l'animazione è in pausa e io clicco su una delle icone degli explorer per andare _on board_, l'animazione riparta in automatico.

**Comment by iacopolea** [comment]
@angeloseme, questo accade da poco, abbiamo introdotto involontariamente qualche modifica nel file visualization forse?
