### ISSUE TITLE
Explorer details

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#2]
- [x] Sostituire la data corrispondente al giorno: ad esempio, "18 February 2018" invece di "Day 1".  

- [x] aggiungere la virgola per le migliaia, nel valore del campo "Distance": 15,058 km invece di 15058 km;

- [x] eliminare i decimali nel valore del campo "Current Speed", approssimando al valore intero più vicino: 55 km/h invece di 55.42 km/h. Inoltre, chiamerei questo campo "Speed", eliminando "current".

- [x] anche se non calcolata in maniera precisa, aggiungerei comunque l'indicazione dell'altitudine, perché è un dato che alla fine visualizziamo nella traiettoria, ed è importante per capire la dinamica di volo degli explorer fra notte e giorno. Metterei, quindi, un campo "Altitude" fra "Distance" e "Speed".

<img width="234" alt="screen shot 2018-02-16 at 12 37 37" src="https://user-images.githubusercontent.com/6624862/36377208-9aae92ea-1576-11e8-97e4-5a05421b7ec0.png">

**Comment by iacopolea** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explorer details #2](https://trello.com/c/aoTDBbjp/39-explorer-details-2)
