### ISSUE TITLE
Indicazione dell'altitudine in modalità Onboard

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#21]
È corretto che nella modalità onboard l'altitudine dell'Explorer rimanga fissa sui 10km? (vedi screenshot). Credo, invece, che ci debba essere un'oscillazione che rispecchi l'effettivo cambio di altitudine che avviene fra notte e giorno. Inoltre, **userei i metri come unità di misura**.

![screen shot 2018-03-06 at 14 42 14](https://user-images.githubusercontent.com/6624862/37035429-d511ce8e-214c-11e8-83f5-c1a9dfba23f6.png)

**Comment by iacopolea** [comment]
@angeloseme Questo dobbiamo ancora implementarlo lato backend, giusto?

**Comment by mariofaranda** [comment]
Ho visto che adesso l'indicazione della'altitudine è dinamica (super!), però forse c'è un errore nell'unità di misura? (vedi screenshot). @angeloseme 
![screen shot 2018-03-08 at 19 37 21](https://user-images.githubusercontent.com/6624862/37169486-4de55e0e-2308-11e8-9fdd-db5e11ff8f32.png)
