### ISSUE TITLE
Gallery non rispondente a design

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#22]
Il layout della gallery non corrisponde al design. Verificare [link InVision](https://projects.invisionapp.com/d/main#/console/13062924/273253721/preview) per layout corretto. In particolare:

- [x] Colore aeroglifo

- [x] icona che segnala l'inizio del percorso

- [x] informazioni aggiuntive nell'etichetta che compare in hover, come da design più recente di Luca.

![screen shot 2018-03-06 at 14 45 03](https://user-images.githubusercontent.com/6624862/37035570-3ea64cc6-214d-11e8-96b9-351400bf5e66.png)

**Comment by iacopolea** [comment]
@angeloseme abbiamo implementato colore e icona di inizio percorso già per l'aeroglifo che appare a fine volo, ma quando salviamo il tutto facendo un _post_ su db/insert.php succede qualcosa.
Oltre al problema che dice Marco ho notato che l'immagine riproposta nella gallery è diversa da quella mostrata nel modal di fine volo. Le immagini della gallery sono parecchio standard, considerato la diversità delle location di arrivo e partenza che abbiamo adesso, non mi spiego questa uniformità.
Dunque o le salviamo male o le recuperiamo nel modo sbagliato.
