### ISSUE TITLE
Numbers of KMs travelled

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#25]
Credo ci sia un bug nel calcolo dei numeri di KMs totali nella galleria, sono decisamente troppo pochi (sia per singolo aeroglifo salvato, che per il totale calcolato subito sotto il paragrafo introduttivo). ad esempio, in questo screenshot, si vede come un explorer che è stato in volo per 15 giorni, secondo il testo abbia viaggiato per soli 28 km...

![screen shot 2018-03-09 at 08 39 09](https://user-images.githubusercontent.com/6624862/37196046-84a81702-2375-11e8-9f07-5411ab5a6d2c.png)

**Comment by iacopolea** [comment]
@angelo secondo te è una cosa da backend?
Io prendo min_distance per la distanza minima tra _arrival_ e _explorer_ e distance per il totale dei km viaggiati. Anche se sembra quasi il contrario.

**Comment by angeloseme** [comment]
Si, si tratta di unità di misura diverse. Distance è in migliaia di km e min_distance è in km. Uniformerò i valori in km. Per quanto riguarda total_distance, direi di lasciarlo in migliaia di km.

**Comment by iacopolea** [comment]
No problem, mi ero perso questa differenza. ho aggiunto un * 1000 e è ok
