### ISSUE TITLE
Explorer schizofrenici

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#32]
C'è un bug abbastanza evidente che succede quando si riavvia un volo mentre il precedente è ancora in corso (a me, ad esempio, viene fuori quando clicco "Start a New Aerosolar Journey" dal menu senza aver aspettato che il volo precedente fosse terminato. Quello che succede è che nel nuovo volo gli Explorer partono da punti apparentemente casuali del globo, come se continuassero un volo precedente... qui alcuni screenshot dove forse si capisce meglio.

Credo questo isa anche collegato a quelle traiettorie strane che ogni tanto appaiono nella Gallery, in cui delle linee rette collegano punti a caso della traiettoria curvilinea.

![screen shot 2018-03-12 at 13 32 37](https://user-images.githubusercontent.com/6624862/37283874-db2da926-25f9-11e8-82b2-607057a55e57.png)

![screen shot 2018-03-12 at 13 27 42](https://user-images.githubusercontent.com/6624862/37283808-a42f17d4-25f9-11e8-9e74-5eeefc031472.png)
![screen shot 2018-03-12 at 13 26 13](https://user-images.githubusercontent.com/6624862/37283809-a524a7bc-25f9-11e8-8578-7a8ec78b17a2.png)
![screen shot 2018-03-12 at 13 25 25](https://user-images.githubusercontent.com/6624862/37283819-aa44ac24-25f9-11e8-9465-4a0a2bb253e2.png)

**Comment by angeloseme** [comment]
Dovrebbe essere risolto con l'ultimo commit. @mariofaranda potresti testare l'ultima versione che ho caricato su tmp?

**Comment by mariofaranda** [comment]
@angeloseme Confermo! 🙏
