### ISSUE TITLE
Aeroglyph JSON

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#34]
[non urgente]

Angelo, sto finendo di scrivere la pagina "Resources and APIs" per il sito, e volevo descrivere con precisione i campi del file JSON. Attualmente quello che si scarica dalle API ha questa struttura:

`{"id","page","created","departure","destination":{"city","country","coordinates"},"min_dist","min_time","speed","timestamp","path","email","comment"}`

Ho un paio di domande:

- cosa indica "page"? 

- "email" e "comment" vanno eliminati, dal momento che non vogliamo distribuire gli indirizzi mail raccolti tramite il form finale, e i commenti non ci sono più—giusto? Forse potremmo aggiungere un campo "name" che includa eventualmente il nome delle persone che lo lasciano? Oppure questo dato, essendo alla fine archiviato su Mailchimp, non può essere raccolto dal JSON?

- il colore della traiettoria è archiviato da qualche parte (dentro "path"), oppure si basa sul giorno del lancio?

**Comment by angeloseme** [comment]
- risultati vengono ritornati in pagine da 30 voli. Nella pagina 1 ci saranno i 30 voli più recenti, nella pagina due i voli che vanno da 30 a 60, e così via. Se pensi sia un'informazione superflua possiamo toglierla.
- email e comment sono stati eliminati.
- Il colore della traiettoria non viene salvato. Questa info è salvata nell'svg come colore e può essere calcolata sottraendo la data di partenza con quella di creazione.

**Comment by mariofaranda** [comment]
OK! Forse "page" può essere tolto se non serve al corretto caricamento degli aeroglifi in galleria...

**Comment by angeloseme** [comment]
rimosso
