### ISSUE TITLE
Aerocene Explorers hover

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#36]
Al momento non c'è abbastanza corrispondenza fra le icone degli Explorer sulla destra dello schermo e la loro visualizzazione. Così come quando si va in hover sulle icone nella visualizzazione compare il profilo 3D della traiettoria, questo dovrebbe comparire anche quando si va in hover sulle icone laterali, **ma senza mettere in pausa la simulazione**.

**Comment by angeloseme** [comment]
@iacopolea ho aggiunto allo store la variabile selectedExplorer, simile a focusedExplorer, utile per sincronizzare le selezioni

**Comment by mariofaranda** [comment]
@angeloseme Abbiamo implementato l'hover anche nelle icone laterali, però, se fosse possibile, bisognerebbe modificare il comportamente dei due hover: quando faccio hover sugli explorer all'interno della viz, questa va giustamente in pausa; quando faccio hover sulle icone laterali, la viz _non_ dovrebbe andare in pausa. Cosa ne pensi?

**Comment by mariofaranda** [comment]
@angeloseme C'è un piccolo bug quando si selezionano gli explorer dalle icone laterali: il cerchio semitrasparente che viene utilizzato per evidenziare gli explorer nella visualizzazione rimane fermo, mentre l'explorer continua ad andare avanti... si può aggnaciare il cerchio all'explorer, in modo che lo segua?

<img width="690" alt="screen shot 2018-03-23 at 10 08 02" src="https://user-images.githubusercontent.com/6624862/37820885-4c58cad2-2e82-11e8-917e-5e12f0274660.png">
