### ISSUE TITLE
New parameters for visualisation

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#41]
**GENERAL**

- **speed_d_x_sec**: 0.105

**ONBOARD**

- **camera_distance**: 1.3

**LIGHTS**

- **spot_light_intensity**: 0.8

**WIND** (WHITE, animated)

- **RGB Mapping**
- **opacity_mapping**: ON
- **start_color**: #5b5b5b
- **threshold**: 25
- **opacity**: 0.9
- **magnitude**: 0.4

**WIND** (WHITE, static)

- **RGB Mapping**
- **opacity_mapping**: ON
- **start_color**: #5b5b5b
- **threshold**: 25
- **opacity**: 0.4
- **magnitude**: 0.25

**WIND** (COLOUR, animated)

- **HUE Mapping**
- **opacity_mapping**: ON
- **threshold**: 25
- **opacity**: 0.9
- **magnitude**: 0.5

**WIND** (COLOUR, static)

- **HUE Mapping**
- **opacity_mapping**: ON
- **threshold**: 30
- **opacity**: 0.4
- **magnitude**: 0.25

**Comment by angeloseme** [comment]
@mariofaranda  puoi modificare direttamente i parametri qui, o se vuoi faccio io:
Web: [https://github.com/StudioFolder/aerocene/blob/master/static/config/general.json](url)
Exhibition: [https://github.com/StudioFolder/aerocene/blob/exhibition/static/config/general.json]()

**Comment by mariofaranda** [comment]
@angeloseme: Ok, perfetto, posso fare io! Quando li cambio devo avvisarvi, oppure la visualizzazione online viene direttamente aggiornata quando fate un push?

**Comment by mariofaranda** [comment]
Altra domanda: mi sembra di vedere dei parametri unici per tutti i venti, invece avremmo bisogno di definire delle variabili diverse per le 4 opzioni (animated/static, white/colour), come del resto mi sembra abbiamo già fatto nell'ultima modifica, no?

**Comment by angeloseme** [comment]
@mariofaranda  ora puoi modificare nel file general.json le 5 configurazioni di venti, campo wind_settings.

**Comment by angeloseme** [comment]
e puoi vedere le modifiche quando facciamo push sul server

**Comment by mariofaranda** [comment]
Super!
