### ISSUE TITLE
Scomparsa Aerocene logo

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#42]
Quando si clicca su "Re-centre" per la prima volta durante l'animazione, il logo in alto a sinistra scompare. Dovrebbe invece essere sempre presente in tutte le fasi di utilizzo del sito.

**Comment by iacopolea** [comment]
Non riesco a riprodurre il bug. Se clicco su recentre la prima o le volte successive il logo resta al suo posto

**Comment by mariofaranda** [comment]
Credo che questo bug fosse stato risolto, quindi si ouò chiudere il thread
