### ISSUE TITLE
Dimensione etichette 3D

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#46]
Ci sarebbe da migliorare la visualizzazione delle etichette, che al momento non scalano a seconda del livello di zoom. Specialmente nella modalità onboard, appaiono troppo grandi, e si sovrappongono molto nelle zone in cui si cono città importanti vicine. Le etichette dovrebbero rimpicciolirsi quando si zooma più vicino alla sfera, in modo che mantengano sempre la stessa dimensione assoluta. Inoltre, avvicinerei maggiormente il testo al pin di localizzazione sulla mappa, in modo che non si crei confusione fra città vicine. 
![screen shot 2018-03-17 at 10 52 41](https://user-images.githubusercontent.com/6624862/37553947-bfb77fc4-29d1-11e8-83c8-edb0a8e975ea.png)

**Comment by iacopolea** [comment]
se è ok chiudo l'issue

**Comment by angeloseme** [comment]
Si ok. Chiudo!
