### ISSUE TITLE
Initial globe animation

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#5]
Attualmente, una volta inseriti i punti di partenza e destinazione, l'animazione del globo procede prima ruotando la terra per centrare il punto di partenza, e solo poi zoomando all'esterno in modo da inquadrare tutto il globo (quando la simulazione è già avviata). Bisogna, invece, avere un'**animazione combinata di questi due movimenti**, in modo che la simulazione parta con il punto di partenza sempre visibile al centro dell'inquadratura.

**Comment by iacopolea** [comment]
Ora l'animazione è ok
