### ISSUE TITLE
Selecting the Explorer by their icons

### ISSUE THREAD

**Issue by mariofaranda** [StudioFolder/aerocene#6]
Bisognerebbe far sì che si possa passare da un Exlporer all'altro (per la modalità onboard), **cliccando sull'icona** dei singoli Explorer all'interno della visualizzazione (e non solo dai controller a destra nell'UI). Quindi, le icone 3D degli Explorer dovrebbero essere sempre cliccabili, sia quando si è già in modalità onboard (per passare da un Explorer ad un altro), sia quando si è nella vista generale (per selezionarli direttamente nella visualizzazione).

**Comment by iacopolea** [comment]
implemented in last release
