### ISSUE TITLE
Label distorted

### ISSUE THREAD

**Issue by Lucawist** [StudioFolder/aerocene#75]
A volte (non si capisce esattamente quando) le etichette sono distorte quando si entra nelle pagine di testo. 
![screen shot 2018-04-16 at 11 01 50](https://user-images.githubusercontent.com/9106361/38799772-b14b0446-4165-11e8-968d-7af950bd08a7.png)

**Comment by angeloseme** [comment]
Ora dovrebbe essere ok. Potresti fare un test @Lucawist e se ok, chiudi pure la issue.
